################################
# GitHub https://github.com/raydak-labs/configarr
# Documentation https://configarr.de/docs/configuration/config-file/
################################

# Optional: Override default repositories
# trashGuideUrl: https://github.com/TRaSH-Guides/Guides
# trashRevision: master # Optional to specify sha
# recyclarrConfigUrl: https://github.com/recyclarr/config-templates
# recyclarrRevision: master # Optional to specify sha

# Optional: Enable anonymous telemetry tracking of feature usage
# Default is false. Set to true to help improve Configarr by sharing anonymous usage statistics.
# telemetry: true

# Optional: Paths for custom formats and templates
# localCustomFormatsPath: /opt/configarr/cfs
# localConfigTemplatesPath: /opt/configarr/templates

customFormatDefinitions:
  - trash_id: ukrainian-language-cf
    trash_scores:
      default: 100  # Adjust this score based on your preference
    trash_description: "Language: Ukrainian Audio/Subs"
    name: "Language: Ukrainian"
    includeCustomFormatWhenRenaming: true
    specifications:
      - name: Ukrainian Audio
        implementation: LanguageSpecification
        negate: false
        required: false
        fields:
          value: 38  # Ukrainian language code
      - name: Ukrainian Subtitles
        implementation: LanguageSpecification
        negate: false
        required: false
        fields:
          value: 38
          part: subtitles

sonarr:
  instance1:
    # Set the URL/API Key to your actual instance
    base_url: http://sonarr:8989
    api_key: !secret SONARR_API_KEY

    # Optional: For disabling instances
    # enabled: false

    # Optional: For deleting unmanaged formats
    delete_unmanaged_custom_formats:
      enabled: true
    #   ignore:
    #     - CustomFormatToKeep

    # Optional: Root folders
    root_folders:
      - /mnt/tvshows

    # Media Naming Configuration
    media_naming:
      series: default
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

    media_management:
      autoUnmonitorPreviouslyDownloadedEpisodes: true
      chmodFolder: "755"
      chownGroup: ""
      copyUsingHardlinks: true
      createEmptySeriesFolders: false
      deleteEmptyFolders: true
      downloadPropersAndRepacks: preferAndUpgrade
      enableMediaInfo: true
      episodeTitleRequired: always
      extraFileExtensions: srt
      fileDate: none
      importExtraFiles: true
      minimumFreeSpaceWhenImporting: 10240 # in MB
      recycleBin: "/tmp"
      recycleBinCleanupDays: 7
      rescanAfterRefresh: always
      scriptImportPath: ""
      setPermissionsLinux: false
      skipFreeSpaceCheckWhenImporting: false
      useScriptImport: false

    quality_definition:
      type: series

    include:
      - template: sonarr-quality-definition-series
      - template: sonarr-v4-quality-profile-web-2160p-alternative
      - template: sonarr-v4-custom-formats-web-2160p

    custom_formats:
      # Language Custom Format
      - trash_ids:
          - ukrainian-language-cf
        assign_scores_to:
          - name: WEB-2160p

      # HDR Formats
      - trash_ids:
          # Comment out the next line if you and all of your users' setups are fully DV compatible
          # - 9b27ab6498ec0f31a3353992e19434ca # DV (w/o HDR fallback)

          # HDR10+ Boost - Uncomment the HDR10+ Boost line if you want to prefer HDR10+ releases
          # DV Boost - Uncomment the DV Boost line if you want to prefer DV releases
          # Uncomment both lines if you want to prefer both (DV HDR10+)
          - 0c4b99df9206d2cfac3c05ab897dd62a # HDR10+ Boost
          - 7c3a61a9c6cb04f52f1544be6d44a026 # DV Boost
        assign_scores_to:
          - name: WEB-2160p

      - trash_ids:
        # Uncomment the next six lines to allow x265 HD releases with HDR/DV
          - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        assign_scores_to:
          - name: WEB-2160p
            score: 0
      - trash_ids:
          - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        assign_scores_to:
          - name: WEB-2160p

      # Optional SDR
      # Only ever use ONE of the following custom formats:
      # SDR - block ALL SDR releases
      # SDR (no WEBDL) - block UHD/4k Remux and Bluray encode SDR releases, but allow SDR WEB
      - trash_ids:
          - 2016d1676f5ee13a5b7257ff86ac9a93 # SDR
          # - 83304f261cf516bb208c18c54c0adf97 # SDR (no WEBDL)
        assign_scores_to:
          - name: WEB-2160p

radarr:
  instance1:
    # Set the URL/API Key to your actual instance
    base_url: http://radarr:7878
    api_key: !secret RADARR_API_KEY

    # Optional: For disabling instances
    #enabled: false

    # Optional: For deleting unmanaged formats
    delete_unmanaged_custom_formats:
      enabled: true
    #   ignore:
    #     - CustomFormatToKeep

    # Optional: Root folders
    root_folders:
      - "/mnt/movies"

    # Media Naming Configuration
    media_naming:
      folder: default
      movie:
        rename: true
        standard: default

    media_management:
      autoRenameFolders: false
      autoUnmonitorPreviouslyDownloadedMovies: true
      chmodFolder: "755"
      chownGroup: ""
      copyUsingHardlinks: true
      createEmptyMovieFolders: false
      deleteEmptyFolders: true
      downloadPropersAndRepacks: preferAndUpgrade
      enableMediaInfo: true
      extraFileExtensions: srt
      fileDate: none
      importExtraFiles: false
      minimumFreeSpaceWhenImporting: 10240 # in MB
      pathsDefaultStatic: false
      recycleBin: /tmp
      recycleBinCleanupDays: 7
      rescanAfterRefresh: always
      scriptImportPath: ""
      setPermissionsLinux: false
      skipFreeSpaceCheckWhenImporting: false
      useScriptImport: false

    quality_definition:
      type: movie

    include:
      # Comment out any of the following includes to disable them
      - template: radarr-quality-definition-movie
      - template: radarr-quality-profile-remux-web-2160p
      - template: radarr-custom-formats-remux-web-2160p

    custom_formats:
      # Language Custom Format
      - trash_ids:
          - ukrainian-language-cf
        assign_scores_to:
          - name: Remux + WEB 2160p

      - trash_ids:
      # Audio
          # Uncomment the next section to enable Advanced Audio Formats
          # - 496f355514737f7d83bf7aa4d24f8169 # TrueHD Atmos
          # - 2f22d89048b01681dde8afe203bf2e95 # DTS X
          # - 417804f7f2c4308c1f4c5d380d4c4475 # ATMOS (undefined)
          # - 1af239278386be2919e1bcee0bde047e # DD+ ATMOS
          # - 3cafb66171b47f226146a0770576870f # TrueHD
          # - dcf3ec6938fa32445f590a4da84256cd # DTS-HD MA
          # - a570d4a0e56a2874b64e5bfa55202a1b # FLAC
          # - e7c2fcae07cbada050a0af3357491d7b # PCM
          # - 8e109e50e0a0b83a5098b056e13bf6db # DTS-HD HRA
          # - 185f1dd7264c4562b9022d963ac37424 # DD+
          # - f9f847ac70a0af62ea4a08280b859636 # DTS-ES
          # - 1c1a4c5e823891c75bc50380a6866f73 # DTS
          # - 240770601cc226190c367ef59aba7463 # AAC
          # - c2998bd0d90ed5621d8df281e839436e # DD
        assign_scores_to:
          - name: Remux + WEB 2160p

      # Movie Versions
      - trash_ids:
      # Uncomment any of the following lines to prefer these movie versions
          # - 0f12c086e289cf966fa5948eac571f44 # Hybrid
          # - 570bc9ebecd92723d2d21500f4be314c # Remaster
          # - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
          # - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
          # - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
          # - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
          # - 957d0f44b592285f26449575e8b1167e # Special Edition
          # - eecf3a857724171f968a66cb5719e152 # IMAX
          # - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        assign_scores_to:
          - name: Remux + WEB 2160p


      - trash_ids:
          # Uncomment the next six lines to allow x265 HD releases with HDR/DV
          - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
        assign_scores_to:
          - name: Remux + WEB 2160p
            score: 0
      - trash_ids:
          - 839bea857ed2c0a8e084f3cbdbd65ecb # x265 (no HDR/DV)
        assign_scores_to:
          - name: Remux + WEB 2160p

      - trash_ids:
          # Comment out the next line if you and all of your users' setups are fully DV compatible
          #- 923b6abef9b17f937fab56cfcf89e1f1 # DV (w/o HDR fallback)

          # HDR10+ Boost - Uncomment the HDR10+ Boost line if you want to prefer HDR10+ releases
          # DV Boost - Uncomment the DV Boost line if you want to prefer DV releases
          # Uncomment both lines if you want to prefer both (DV HDR10+)
          - b337d6812e06c200ec9a2d3cfa9d20a7 # DV Boost
          - caa37d0df9c348912df1fb1d88f9273a # HDR10+ Boost
        assign_scores_to:
          - name: Remux + WEB 2160p

      # Optional SDR
      # Only ever use ONE of the following custom formats:
      # SDR - block ALL SDR releases
      # SDR (no WEBDL) - block UHD/4k Remux and Bluray encode SDR releases, but allow SDR WEB
      - trash_ids:
          - 9c38ebb7384dada637be8899efa68e6f # SDR
          # - 25c12f78430a3a23413652cbd1d48d77 # SDR (no WEBDL)
        assign_scores_to:
          - name: Remux + WEB 2160p

whisparrEnabled: false
readarrEnabled: false
lidarrEnabled: false
